"""Add families and users tables

Revision ID: 1fb620114864
Revises: 
Create Date: 2025-10-13 13:03:20.002520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb620114864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_grocery_items_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_meals_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_family_id', 'families', ['family_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_family_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_family_id', type_='foreignkey')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meals_family_id', type_='foreignkey')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grocery_items_family_id', type_='foreignkey')
        batch_op.drop_column('family_id')

    op.drop_table('users')
    op.drop_table('families')
    # ### end Alembic commands ###
